### PR TITLE
Add important badges to project README

### PR DESCRIPTION
**Pull request by mhujer**
This PR adds some important badges to project README.

See https://github.com/mhujer/steward/tree/add-badges for live preview

//cc @OndraM

### CODE REVIEW

**Comment by mhujer** [comment]
image

**Comment by OndraM** [comment]
I like, but was a bit busy lately :). 

And actually, I was thinking about badges from https://shields.io, what do you think? Don't know a difference from technical POV and relation of poser to shields.io, but their flat version looks a bit nicer for me :-).

Eg.:

**Comment by TomasVotruba** [comment]
I was thinking about same PR preferring shields.io as well. It's easier to maintain/extend.

**Comment by mhujer** [comment]
I am fine with whatever badges you like. So the shields are OK.

**Pull request closed without merging**
