### PR TITLE
Steward binary is called just "steward" for better portability

### LINKED ISSUE #21: bin/steward.php should be just bin/steward
Installing Selenium (https://github.com/lmc-eu/steward#2-install-selenium) using
`$ ./vendor/bin/steward.php install` does not work in Windows (you have to use steward.php.bat).

PHPUnit has `bin/phpunit` and `bin/phpunit.bat` which works fine.

### PR DESCRIPTION
**Pull request by mhujer**
On Windows Composer creates a .bat file for the binary.
If the binary is called `steward.php`, Windows binary becames `steward.php.bat`, therefore launching `steward.php` does not work. On the other hand, if the binary is called just `steward` (should work fine on Linux), `.bat` is appended on Windows and launching `steward` launches that `bat` file.

PHPUnit uses same convention: https://github.com/sebastianbergmann/phpunit

//Note: _It is possible BC break_

Closes #21

### CODE REVIEW

**Comment by OndraM** [comment]
Why has the permissions of steward.php file changed from 0755 to 0644? It needs to stay executable, so you can start it directly on unix-based OS.

**Comment by mhujer** [comment]
Because I renamed it on Windows and they don't care much about permissions :-(

Can you change the permissions back? You should be able to push a commit to this branch

**Comment by OndraM** [comment]
You should be IMHO able to execute something like:

```
git update-index --chmod=755 steward
```

or

```
git update-index --chmod=+x steward
```

Could you try, please?

**Comment by mhujer** [comment]
Works! Fixed and rebased on upstream/master

**Comment by OndraM** [comment]
I've added symlink which should maintain backward compatibility on unixes (thanks @podlesh for the idea), so it won't eg. break all our jenkins jobs :).

Also the changelog was amended.

Looks fine to merge for me now.

**Comment by mhujer** [comment]
:+1:

**Pull request merged**
