### PR TITLE
Readme: badges added

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref #23, [preview](https://github.com/TomasVotruba/steward/blob/patch-2/README.md)

In order of name (and possible interest)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ping?

**Comment by OndraM** [comment]
Sorry, I'm currently away from computer for two+ weeks. I will take a look after I get back :-).

**Comment by TomasVotruba** [comment]
@OndraM Ok, thanks for update.

**Comment by OndraM** [comment]
Remotely merged, thanks!

**Comment by TomasVotruba** [comment]
:+1:

**Pull request closed without merging**
