### PR TITLE
Added property annotation for SyntaxSugarTrait property wd

### PR DESCRIPTION
**Pull request by MortalFlesh**

### CODE REVIEW

**Comment by OndraM** [comment]
But the `$wd` property is actually not added by the trait, so it IMO shloud not contain its annotation - the original class that is being extended by the trait should (and I think it does - see https://github.com/lmc-eu/steward/blob/master/src/Test/AbstractTestCaseBase.php#L12 and https://github.com/lmc-eu/steward/blob/master/src/Component/AbstractComponent.php#L23).

Where do you have problem with the annotation not working? What IDE in which version do you use?

**Comment by MortalFlesh** [comment]
If you open just trait file and want to know how does it work and what its representing, you actually don't know what $wd property is and IDE doesn't know it. So you cant click through methods to their implementation.

**Comment by OndraM** [comment]
Ok, makes sense. Thanks!

**Comment by OndraM** [comment]
Ok, makes sense. Could you @MortalFlesh please resolve the conflicts? I'll merge it then.

**Comment by OndraM** [comment]
Thanks @MortalFlesh!

**Pull request merged**
